### ISSUE TITLE
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by CoolLKKPS** [mattymatty97/LTC_AdditionalNetworking#1]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
AdditionalNetworking.Components.ShotgunNetworking.RequestSyncServerRpc (Unity.Netcode.NetworkObjectReference shotgunReference, Unity.Netcode.ServerRpcParams serverRpcParams) (at ./src/Components/ShotgunNetworking.cs:134)
AdditionalNetworking.Components.ShotgunNetworking.__rpc_handler_3275660569 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <f78acda3ec7d4895acb4ad80a0451086>:0)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:0)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Logger:LogException(Exception, Object)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass4_0:<LogException>b__0() (at ./src/Wrappers/Unity/AsyncLoggerWrapper.cs:36)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass28_0:<wrapCallback>b__0() (at ./src/Wrappers/Unity/AsyncLoggerWrapper.cs:136)
AsyncLoggers.Wrappers.JobWrapper:LogWorker() (at ./src/Wrappers/JobWrapper.cs:84)
AsyncLoggers.Wrappers.LogJob:Execute() (at ./src/Wrappers/JobWrapper.cs:68)
Unity.Jobs.JobStruct`1:Execute(LogJob&, IntPtr, IntPtr, JobRanges&, Int32)

**Comment by mattymatty97** [comment]
😂 i copied the Boombox code from the ShotgunOne and forgot to change one reference from ShotgunNetworking to BoomboxNetworking
