### ISSUE TITLE
[Issue] grab something too fast when as host can make everything cannot interactable and grabable

### ISSUE THREAD

**Issue by CoolLKKPS** [mattymatty97/LTC_AdditionalNetworking#2]
will have this [info] log:
grabInvalidated: False

that might from ur lobby control mod? idk

**Comment by mattymatty97** [comment]
i've seen that happen a couple of times, but i'm not sure if it is from my mods or from vanilla itself

**Comment by CoolLKKPS** [comment]
most like vanilla issue, but can u fix that?

**Comment by CoolLKKPS** [comment]
@mattymatty97 wait actually if i disable this mod, other player who has this mod cannot join my lobby, weird

**Comment by mattymatty97** [comment]
i'm still experimenting with it but if they have LobbyCompatibility that will prevent them from joining hosts with not matching mods

**Comment by mattymatty97** [comment]
i mixed two messages:
i'm still experimenting with the networking but i did test that a client with the mod would be able to join a host w/o it

i have listed the mod as ClientOptional on LobbyCompatibility so if you and/or they have it it will prevent them from joining if the host does not have the mod

**Comment by CoolLKKPS** [comment]
uh i have LobbyCompatibility installed so should be this problem

**Comment by CoolLKKPS** [comment]
i got a temporary solution now, just let u know
