### ISSUE TITLE
[Vanilla Conflict] Alert, vanilla client are updated 13 hours ago and this mod will block vanilla clients to join

### ISSUE THREAD

**Issue by CoolLKKPS** [mattymatty97/LTC_AdditionalNetworking#4]
@mattymatty97

**Comment by CoolLKKPS** [comment]
v0.0.9

**Comment by CoolLKKPS** [comment]
ok i think u make this mod require both-clients side installed, so this issue might be false, but in my opinion it should be server-side, so i may will uninstall this mod due both-clients needed mod

**Comment by mattymatty97** [comment]
yeah i had to convert it to an everyone mod as unity was complaining when a client had to relog

**Comment by mattymatty97** [comment]
it cannot be a server only mod, as it is required to have the mod to receive the packets

**Comment by CoolLKKPS** [comment]
in my expect, if client doesn't install this mod, they still can join the lobby if host installed this mod, but now they can't

**Comment by mattymatty97** [comment]
yeah and before people needed to reboot the entire game to join a lobby

**Comment by mattymatty97** [comment]
sadly we can only blame unity

**Comment by CoolLKKPS** [comment]
ok :(

**Comment by mattymatty97** [comment]
i'll try again in the future but my priority is making the logic work
