### ISSUE TITLE
[Tiny Bug?] Join animation is being skipped

### ISSUE THREAD

**Issue by broken-usb** [mattymatty97/LTC_AdditionalNetworking#5]
When joining a Vanilla lobby with the mod installed the join animation/wake up animation, or whatever you want to call it, gets skipped for you. I'm not sure if this is intended or not but either way its a very small bug.

**Comment by broken-usb** [comment]
Forgot to mention that im using the Experimental branch.

**Comment by mattymatty97** [comment]
it's definitely not intended, could you send logs and possibly a clip of the issue?

**Comment by broken-usb** [comment]
Clip here:

https://github.com/user-attachments/assets/ed276497-c582-4ce4-8885-0cee5b4c3994

As you can see i am able to start moving as soon as joining the lobby since the spawning animation was skipped, this only happens if i have Additional Networking installed.
Log here (i also enabled Verbose):
[LogOutput.log](https://github.com/user-attachments/files/16566514/LogOutput.log)

**Comment by mattymatty97** [comment]
ok found the issue and the error. sadly i wont be able to fix this until the 19th or later.

**Comment by KleskReaver** [comment]
Not sure if this helps but im not getting this issue of skipping the animation, but im not running experimental version :)

**Comment by mattymatty97** [comment]
i've found an exception tha means i did the Networking wrong. so i assumed that was causing the animation to be skipped.

but thinking about it again i do not have any code running before or during the animation so nothing in this mod should be able to skip it

the log @broken-usb sent contains few mods that do actually provide the animation skip as a feature, so i'm wondering if you maybe have it enabled and just did not know/notice before

**Comment by mattymatty97** [comment]
nvm it's indeed experimenal. it's crashing the spawn routine. for now rollback to stable. and we'll see on the next experimental build later this month

**Comment by broken-usb** [comment]
This seems to be fixed on the most recent version, will close for now.
