### ISSUE TITLE
Errors-Exception Caught: System.TypeLoadException

### ISSUE THREAD

**Issue by takaqiao** [mattymatty97/LTC_AdditionalNetworking#7]
[11:48:46.2693178] [Error  :UnityDebuggerAssistant] 

--- Exception Handler ---

Exception Caught: System.TypeLoadException
Assembly: AdditionalNetworking

  Plugin Info
    GUID:     mattymatty.AdditionalNetworking
    NAME/VER: AdditionalNetworking@2.1.2
    LOCATION: \plugins\mattymatty-AdditionalNetworking\AdditionalNetworking.dll

Message: Could not resolve type with token 01000054 from typeref (expected class 'AsyncLoggers.DBAPI.SqliteLogger' in assembly 'AsyncLoggers, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null')
Source: AdditionalNetworking

  --- Begin Frames ---

  --FRAME 1:
    In Assembly: AdditionalNetworking
    Source: ./src/Dependency/AsyncLoggerProxy.cs:47,17
    Target Method: AsyncLoggerProxy.get_Enabled

  --- End Frames ---

--- End Exception Handler ---

**Comment by mattymatty97** [comment]
Refer to UnityDebugAssistant thread
